from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional

class Complainant(BaseModel):
    name: str = Field(title="Name")
    f_or_h_name: str = Field(title="Father's or Husband's Name")
    email: str = Field(title="Email")
    phone: int = Field(title="Phone Number")
    address: str = Field(title="Address")
    age: int = Field(title="Age")
    occupation: str = Field(title="Labourer")
    religion: str = Field(title="Religion")
    caste: str = Field(title="Caste")
    passport_no: str = Field(title="Passport Number")
    aadhar_no: str = Field(title="Aadhar Number")
    nationality: str = Field(title="Nationalality")
    sex: str = Field(title="Gender")


class Header(BaseModel):
    fIRNo: str = Field(title="Crime Number")
    sub_division: str = Field(title="Circle/Sub Division")
    district: str = Field(title="District")
    fir_date: str = Field(title="FIR Date")
    unitName: str = Field(title="Police Station Name")

class Occurrence(BaseModel):
    day: str = Field(title="Day of Occurrence of Offence")
    from_date: str = Field(title="From Date of Occurrence")
    to_date: str = Field(title="To Date of Occurrence")
    from_time: str = Field(title="From Time of Occurrence")
    to_time: str = Field(title="To Time of Occurrence")
    info: str = Field(title="Information received at the PS")
    district: str = Field(title="District")
    w_or_o: str = Field(title="Written or Oral")
    delay_reason: str = Field(title="Reason for Delay in reporting by the Complainant/Informant")
    general_diary_no: str = Field(title="General Diary Number")
    place_of_occurrence: str = Field(title="Place of Occurrence with full address")
    distance: str = Field(title="Distance from PS")
    village: str = Field(title="Village")
    beat: str = Field(title="Beat Name")

class Suspect(BaseModel):
    idx: int = Field(title="Sl. No.")
    identifier: str = Field(title="Name or Father's Name or Caste or Address")
    type: str = Field(title="Type of Suspect")
    person_type: str = Field(title="Person Type")
    sex: str = Field(title="Gender")
    age: int = Field(title="Age")
    occupation: str = Field(title="Labourer")

class Victim(BaseModel):
    idx: int = Field(title="Sl. No.")
    name: str = Field(title="Name")
    injury_type: str = Field(title="Type of Injury")
    sex: str = Field("Gender")
    age: int = Field("Age")
    occupation: str = Field("Occupation")

class StolenProperty(BaseModel):
    idx: int = Field(title="Sl. No.")
    property_type: str = Field(title="Type of Property")
    value: str = Field(title="Estimated Value of Property")
    description: str = Field(title="Item Description")


class FIRDetails(BaseModel):
    district: Optional[str] = Field(title="District", json_schema_extra={"is_anonymized": True, "section": 1})
    crime_no: Optional[str] = Field(title="Crime No", json_schema_extra={"is_anonymized": True, "section": 1})
    fir_date: Optional[str] = Field(title="FIR Date", json_schema_extra={"is_anonymized": True, "section": 1})
    circle_sub_division: Optional[str] = Field(title="Circle/Sub Division", json_schema_extra={"is_anonymized": True, "section": 1})
    police_station: Optional[str] = Field(title="PS", json_schema_extra={"is_anonymized": True, "section": 1})
    act_section: Optional[str] = Field(title="Act & Section", json_schema_extra={"is_anonymized": True, "section": 2})
    information_received_at_ps: Optional[str] = Field(title="Information received at the PS", json_schema_extra={"is_anonymized": True, "section": 3})
    information_received_type: Optional[str] = Field(title="Written/Oral", json_schema_extra={"is_anonymized": True, "section": 3})
    information_received_from_time: Optional[str] = Field(title="From Time", json_schema_extra={"is_anonymized": True, "section": 3})
    information_received_to_time: Optional[str] = Field(title="To Time", json_schema_extra={"is_anonymized": True, "section": 3})
    information_received_from_date: Optional[str] = Field(title="From Date", json_schema_extra={"is_anonymized": True, "section": 3})
    information_received_to_date: Optional[str] = Field(title="To Date", json_schema_extra={"is_anonymized": True, "section": 3})
    occurrence_of_offence_day: Optional[str] = Field(title="Occurence of Offence Day", json_schema_extra={"is_anonymized": True, "section": 3})
    general_diary_reference_entry_no: Optional[int] = Field(title="General Diary reference Entry No.", json_schema_extra={"is_anonymized": True, "section": 3})
    general_diary_reference_time: Optional[str] = Field(title="General Diary reference Time", json_schema_extra={"is_anonymized": True, "section": 3})
    place_of_occurrence_address: Optional[str] = Field(title="Place of occurence with full address", json_schema_extra={"is_anonymized": True, "section": 4})
    place_of_occurrence_distance_from_ps: Optional[str] = Field(title="Distance from PS", json_schema_extra={"is_anonymized": True, "section": 4})
    place_of_occurrence_village: Optional[str] = Field(title="Village", json_schema_extra={"is_anonymized": True, "section": 4})
    place_of_occurrence_beat_name: Optional[str] = Field(title="Beat Name", json_schema_extra={"is_anonymized": True, "section": 4})
    place_of_occurrence_district: Optional[str] = Field(title="District", json_schema_extra={"is_anonymized": True, "section": 4})
    complainant_informant_name: Optional[str] = Field(title="Name", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_father_husband_name: Optional[str] = Field(title="Father's/Husband's Name", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_age: Optional[int] = Field(title="Age", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_occupation: Optional[str] = Field(title="Occupation", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_religion: Optional[str] = Field(title="Religion", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_caste: Optional[str] = Field(title="Caste", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_phone_no: Optional[str] = Field(title="Phone No.", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_nationality: Optional[str] = Field(title="Nationality", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_passport_no: Optional[str] = Field(title="Passport No.", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_passport_date_of_issue: Optional[str] = Field(title="Date of Issue", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_address: Optional[str] = Field(title="Address", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_sex: Optional[str] = Field(title="Sex", json_schema_extra={"is_anonymized": True, "section": 5})
    complainant_informant_seen_occurrence: Optional[str] = Field(title="Whether complainant has seen the occurence or merely heard of it", json_schema_extra={"is_anonymized": True, "section": 5})
    accused_details: Optional[dict] = Field(title="Details of known/suspected/unknown accused with full particulars", json_schema_extra={"is_anonymized": True, "section": 6})
    victim_details: Optional[dict] = Field(title="Details of Victims with full particulars", json_schema_extra={"is_anonymized": True, "section": 7})
    stolen_property_details: Optional[dict] = Field(title="Particulars of Property stolen/involved with value", json_schema_extra={"is_anonymized": True, "section": 8})
    inquest_report_ud_case_no: Optional[str] = Field(title="Inquest Report/U.D. Case No. if any", json_schema_extra={"is_anonymized": True, "section": 9})
    fir_contents: Optional[str] = Field(title="F.I.R Contents", json_schema_extra={"is_anonymized": True, "section": 10})
    action_taken: Optional[str] = Field(title="Action Taken", json_schema_extra={"is_anonymized": True, "section": 11}),
    signature = Field(title="Signature/Thumb impression of the complainant", json_schema_extra={"is_anonymized": True, "section": 12})
    fir_dispatch_date_time: Optional[str] = Field(title="Date and time of dispatch to the Court", json_schema_extra={"is_anonymized": True, "section": 13})
    fir_carrier_name: Optional[str] = Field(title="Name of PC/HC who carried the FIR to the Court", json_schema_extra={"is_anonymized": True, "section": 14})


class FIRDetails(BaseModel):
    district_name: Optional[str] = Field(title="District Name", json_schema_extra={"is_anonymized": True})
    unitName: Optional[str] = Field(title="Unit Name", json_schema_extra={"is_anonymized": True})
    fIRNo: Optional[str] = Field(title="FIR Number", json_schema_extra={"is_anonymized": True})
    ri: Optional[int] = Field(title="RI", json_schema_extra={"is_anonymized": True})
    year: Optional[int] = Field(title="Year", json_schema_extra={"is_anonymized": True})
    month: Optional[int] = Field(title="Month", json_schema_extra={"is_anonymized": True})
    offence_from_date: Optional[datetime] = Field(title="Offence From Date", json_schema_extra={"is_anonymized": True})
    offence_to_date: Optional[datetime] = Field(title="Offence To Date", json_schema_extra={"is_anonymized": True})
    fir_reg_datetime: Optional[datetime] = Field(title="FIR Registration DateTime", json_schema_extra={"is_anonymized": True})
    fir_date: Optional[str] = Field(title="FIR Date", json_schema_extra={"is_anonymized": True})
    fir_type: Optional[str] = Field(title="FIR Type", json_schema_extra={"is_anonymized": True})
    fir_stage: Optional[str] = Field(title="FIR Stage", json_schema_extra={"is_anonymized": True})
    complaint_mode: Optional[str] = Field(title="Complaint Mode", json_schema_extra={"is_anonymized": True})
    crimegroup_name: Optional[str] = Field(title="Crime Group Name", json_schema_extra={"is_anonymized": True})
    crimehead_name: Optional[str] = Field(title="Crime Head Name", json_schema_extra={"is_anonymized": True})
    latitude: Optional[float] = Field(title="Latitude", json_schema_extra={"is_anonymized": True})
    longitude: Optional[float] = Field(title="Longitude", json_schema_extra={"is_anonymized": True})
    actSection: Optional[str] = Field(title="Act Section", json_schema_extra={"is_anonymized": True})
    iOName: Optional[str] = Field(title="IO Name", json_schema_extra={"is_anonymized": True})
    kgid: Optional[str] = Field(title="KGID", json_schema_extra={"is_anonymized": True})
    ioassigned_date: Optional[str] = Field(title="IO Assigned Date", json_schema_extra={"is_anonymized": True})
    internal_io: Optional[int] = Field(title="Internal IO", json_schema_extra={"is_anonymized": True})
    place_of_offence: Optional[str] = Field(title="Place of Offence", json_schema_extra={"is_anonymized": True})
    distance_from_ps: Optional[str] = Field(title="Distance from PS", json_schema_extra={"is_anonymized": True})
    beat_name: Optional[str] = Field(title="Beat Name", json_schema_extra={"is_anonymized": True})
    village_area_name: Optional[str] = Field(title="Village Area Name", json_schema_extra={"is_anonymized": True})
    male: Optional[int] = Field(title="Male", json_schema_extra={"is_anonymized": True})
    female: Optional[int] = Field(title="Female", json_schema_extra={"is_anonymized": True})
    boy: Optional[int] = Field(title="Boy", json_schema_extra={"is_anonymized": True})
    girl: Optional[int] = Field(title="Girl", json_schema_extra={"is_anonymized": True})
    age_0: Optional[int] = Field(title="Age 0", json_schema_extra={"is_anonymized": True})
    victim_count: Optional[int] = Field(title="Victim Count", json_schema_extra={"is_anonymized": True})
    accused_count: Optional[int] = Field(title="Accused Count", json_schema_extra={"is_anonymized": True})
    arrested_male: Optional[int] = Field(title="Arrested Male", json_schema_extra={"is_anonymized": True})
    arrested_female: Optional[int] = Field(title="Arrested Female", json_schema_extra={"is_anonymized": True})
    arrested_count_no: Optional[int] = Field(title="Arrested Count No.", json_schema_extra={"is_anonymized": True})
    accused_chargesheeted_count: Optional[int] = Field(title="Accused Chargesheeted Count", json_schema_extra={"is_anonymized": True})
    conviction_count: Optional[int] = Field(title="Conviction Count", json_schema_extra={"is_anonymized": True})
    fir_id: Optional[int] = Field(title="FIR ID", json_schema_extra={"is_anonymized": True})
    unit_id: Optional[int] = Field(title="Unit ID", json_schema_extra={"is_anonymized": True})
    crime_no: Optional[int] = Field(title="Crime No.", json_schema_extra={"is_anonymized": True})


